// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf_spec/order/order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	common "sparrow/api/protobuf_spec/common"
	user "sparrow/api/protobuf_spec/user"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOrderInfoReq struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderInfoReq) Reset()         { *m = GetOrderInfoReq{} }
func (m *GetOrderInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetOrderInfoReq) ProtoMessage()    {}
func (*GetOrderInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a462b80e88bdf51, []int{0}
}

func (m *GetOrderInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderInfoReq.Unmarshal(m, b)
}
func (m *GetOrderInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderInfoReq.Marshal(b, m, deterministic)
}
func (m *GetOrderInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderInfoReq.Merge(m, src)
}
func (m *GetOrderInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetOrderInfoReq.Size(m)
}
func (m *GetOrderInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderInfoReq proto.InternalMessageInfo

func (m *GetOrderInfoReq) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type OrderInfo struct {
	Price                float32        `protobuf:"fixed32,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Address              string         `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	ProductName          string         `protobuf:"bytes,3,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	User                 *user.UserInfo `protobuf:"bytes,4,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a462b80e88bdf51, []int{1}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderInfo) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *OrderInfo) GetUser() *user.UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*GetOrderInfoReq)(nil), "order.GetOrderInfoReq")
	proto.RegisterType((*OrderInfo)(nil), "order.OrderInfo")
}

func init() {
	proto.RegisterFile("api/protobuf_spec/order/order.proto", fileDescriptor_6a462b80e88bdf51)
}

var fileDescriptor_6a462b80e88bdf51 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0x8b, 0x2f, 0x2e, 0x48, 0x4d, 0xd6, 0xcf, 0x2f,
	0x4a, 0x49, 0x2d, 0x82, 0x90, 0x7a, 0x60, 0x19, 0x21, 0x56, 0x30, 0x47, 0x4a, 0x15, 0x53, 0x6d,
	0x72, 0x7e, 0x6e, 0x6e, 0x7e, 0x1e, 0x94, 0x82, 0xa8, 0x96, 0x52, 0xc4, 0x54, 0x56, 0x5a, 0x9c,
	0x5a, 0x04, 0x26, 0x20, 0x4a, 0x94, 0xb4, 0xb9, 0xf8, 0xdd, 0x53, 0x4b, 0xfc, 0x41, 0xa6, 0x7a,
	0xe6, 0xa5, 0xe5, 0x07, 0xa5, 0x16, 0x0a, 0x49, 0x70, 0xb1, 0x83, 0x6d, 0xf1, 0x74, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x1a, 0x19, 0xb9, 0x38, 0xe1, 0x4a, 0x85, 0x44,
	0xb8, 0x58, 0x03, 0x8a, 0x32, 0x93, 0x53, 0xc1, 0xaa, 0x98, 0x82, 0x20, 0x1c, 0x90, 0x6e, 0xc7,
	0x94, 0x94, 0xa2, 0xd4, 0xe2, 0x62, 0x09, 0x26, 0x88, 0x6e, 0x28, 0x57, 0x48, 0x81, 0x8b, 0x3b,
	0xa0, 0x28, 0x3f, 0xa5, 0x34, 0xb9, 0xc4, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x19, 0x2c, 0x8b, 0x2c,
	0x24, 0xa4, 0xc4, 0xc5, 0x12, 0x5a, 0x9c, 0x5a, 0x24, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x6d, 0xc4,
	0xa7, 0x07, 0x76, 0x27, 0x48, 0x04, 0xec, 0x34, 0xb0, 0x9c, 0x91, 0x33, 0x17, 0x2b, 0xd8, 0x09,
	0x42, 0x56, 0x5c, 0x3c, 0xc8, 0x2e, 0x17, 0x12, 0xd3, 0x83, 0x04, 0x14, 0x9a, 0x77, 0xa4, 0x04,
	0xf4, 0xa0, 0x61, 0x12, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0xaa, 0xc4, 0xe0, 0xa4, 0x18,
	0x25, 0x5f, 0x5c, 0x90, 0x58, 0x54, 0x94, 0x5f, 0xae, 0x8f, 0x23, 0xd4, 0x93, 0xd8, 0xc0, 0x82,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x6c, 0x6e, 0xab, 0x97, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around sctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	GetOrderInfo(ctx context.Context, in *GetOrderInfoReq, opts ...grpc.CallOption) (*common.Response, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) GetOrderInfo(ctx context.Context, in *GetOrderInfoReq, opts ...grpc.CallOption) (*common.Response, error) {
	out := new(common.Response)
	err := c.cc.Invoke(ctx, "/order.Order/GetOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	GetOrderInfo(context.Context, *GetOrderInfoReq) (*common.Response, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) GetOrderInfo(ctx context.Context, req *GetOrderInfoReq) (*common.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfo not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_GetOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderInfo(ctx, req.(*GetOrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderInfo",
			Handler:    _Order_GetOrderInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf_spec/order/order.proto",
}
